version: "3"
services:
  mongo:
    container_name: mono-flux
    image: mongo:5.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  mongo-express:
    container_name: mongo-ui
    image: mongo-express:0.54
    ports:
      - 8081:8081